# Generated by Django 5.1.2 on 2024-11-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1000 TO 10000', '1000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('30000 TO 40000', '30000 TO 40000'), ('20000 TO 30000', '20000 TO 30000'), ('40000 TO 50000', '40000 TO 50000')], max_length=60),
        ),
    ]
